# Generated by Django 4.1.1 on 2022-09-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atv', '0002_compra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='nome',
            new_name='peca',
        ),
    ]
