# Generated by Django 4.1.1 on 2022-09-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atv', '0005_compra2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peca', models.CharField(max_length=100)),
                ('cor', models.CharField(max_length=50)),
            ],
        ),
    ]
